import type { BrushTipDescriptor } from '../tipDescriptor'

/** Pack-qualified id for the pixel-art pencil stamp (`proc.square-hard`). */
export const PENCIL_TIP_ID = 'proc.square-hard' as const

const license = {
  spdx: 'MIT',
  pack: 'Happy Round Set',
  source: 'https://github.com/happy-shop/happy-shop',
}

function procedural(
  id: string,
  name: string,
  options: Partial<
    Pick<
      BrushTipDescriptor,
      'hardness' | 'roundness' | 'angle' | 'spacing' | 'defaults' | 'shape'
    >
  > = {},
): BrushTipDescriptor {
  return {
    id: `proc.${id}`,
    name,
    pack: 'proc',
    kind: 'procedural',
    shape: options.shape ?? 'round',
    hardness: options.hardness ?? 0.85,
    roundness: options.roundness ?? 1,
    angle: options.angle ?? 0,
    spacing: options.spacing ?? 0.25,
    defaults: options.defaults ?? {},
    license,
  }
}

/** First-paint-safe analytic tips. Their coverage is generated by dabKernel. */
export const PROCEDURAL_TIPS: readonly BrushTipDescriptor[] = [
  procedural('round-hard', 'Round Hard', { hardness: 1 }),
  procedural('square-hard', 'Square Hard', {
    shape: 'square',
    hardness: 1,
    spacing: 1,
    defaults: { size: 1 },
  }),
  // Keep "soft" perceptually soft: a 35% core leaves a broad feathered rim
  // while the explicit Round Medium/Hard presets retain firm edges.
  procedural('round-soft', 'Round Soft', { hardness: 0.35 }),
  procedural('round-medium', 'Round Medium', { hardness: 0.7 }),
  procedural('round-feather', 'Round Feather', { hardness: 0.35 }),
  procedural('ellipse-25', 'Ellipse 25', { roundness: 0.25 }),
  procedural('ellipse-50', 'Ellipse 50', { roundness: 0.5 }),
  procedural('chisel-flat', 'Chisel Flat', {
    roundness: 0.15,
    spacing: 0.05,
    hardness: 1,
  }),
  procedural('dot-spray', 'Dot Spray', {
    spacing: 0.9,
    hardness: 1,
    defaults: { size: 8 },
  }),
]
